WebApplication1/Models/Issue/AssignmentStatsViewModel.cs
using System.Linq;
using AutoMapper;
using WebApplication1.Domain;
using WebApplication1.Infrastructure.Mapping;

namespace WebApplication1.Models.Issue
{
    public class AssignmentStatsViewModel : IHaveCustomMappings
    {
        public string UserName { get; set; }
        public int Enhancements { get; set; }
        public int Bugs { get; set; }
        public int Support { get; set; }
        public int Other { get; set; }
        public void CreateMappings(IConfiguration configuration)
        {
            Mapper.CreateMap<ApplicationUser, AssignmentStatsViewModel>()
                .ForMember(m => m.Enhancements, o => o.MapFrom(u => u.Assignments.Count(i => i.IssueType == IssueType.Enhancement)))
                .ForMember(m => m.Bugs, o => o.MapFrom(u => u.Assignments.Count(x => x.IssueType == IssueType.Bug)))
                .ForMember(m => m.Support, o => o.MapFrom(u => u.Assignments.Count(x => x.IssueType == IssueType.Support)))
                .ForMember(m => m.Other, o => o.MapFrom(u => u.Assignments.Count(x => x.IssueType == IssueType.Other)));
        }
    }
}

WebApplication1/Models/Issue/EditIssueForm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using WebApplication1.Domain;
using WebApplication1.Filters;
using WebApplication1.Infrastructure.Mapping;

namespace WebApplication1.Models.Issue
{
    public class EditIssueForm : IMapFrom<Domain.Issue>
    {
        [HiddenInput]
        public int IssueId { get; set; }
       
        [ReadOnly(true)]
        public string CreatorUserName { get; set; }
        public string Subject { get; set; }
       

        public IssueType IssueType { get; set; }
        //public SelectListItem[] AvailableIssueTypes { get; set; }

        [Display(Name = "Assigned To")]
        public string AssignedToId { get; set; }
        //public SelectListItem[] AvailableUsers { get; set; }
        [Required]
        public string Body { get; set; }
    }
}

WebApplication1/Models/Issue/IssueDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Domain;
using WebApplication1.Infrastructure.Mapping;

namespace WebApplication1.Models.Issue
{
    public class IssueDetailsViewModel : IMapFrom<Domain.Issue>
    {
        public int IssueId { get; set; }
        public string Subject { get; set; }
        public string CreatorUserName { get; set; }
        public string AssignedToUserName { get; set; }
        public DateTime CreatedAt { get; set; }
        public IssueType IssueType { get; set; }
        public string Body { get; set; }
    }
}

WebApplication1/Models/Issue/IssueSummaryViewModel.cs
using System;
using WebApplication1.Domain;
using WebApplication1.Infrastructure.Mapping;

namespace WebApplication1.Models.Issue
{
    public class IssueSummaryViewModel : IMapFrom<Domain.Issue>
    {
        public int IssueId { get; set; }
        public string Subject { get; set; }
        public DateTime CreatedAt { get; set; }
        public string CreatorUserName { get; set; }
        public IssueType IssueType { get; set; }
        public string AssignedToUserName { get; set; }
    }
}

WebApplication1/Models/Issue/NewIssueForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using WebApplication1.Domain;
using WebApplication1.Filters;
using WebApplication1.Infrastructure.Mapping;

namespace WebApplication1.Models.Issue
{
    public class NewIssueForm:  IHaveCustomMappings
    {
        public string Subject { get; set; }
        [Required]
        public string Body { get; set; }

        public IssueType IssueType { get; set; }
        //public SelectListItem[] AvailableIssueTypes { get; set; }

        [Display(Name = "Assigned To")]
        public string AssignedToUserId { get; set; }
       // public SelectListItem[] AvailableUsers { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<NewIssueForm, Domain.Issue>()
                .ForMember(x => x.CreatedAt, o => o.UseValue(DateTime.Now));
        }
    }
}

WebApplication1/Controllers/IssueController.cs
using AutoMapper.QueryableExtensions;
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Web.Mvc;
using WebApplication1.Domain;
using WebApplication1.Filters;
using WebApplication1.Infrastructure;
using WebApplication1.Infrastructure.Alerts;
using WebApplication1.Infrastructure.Extension;
using WebApplication1.Models;
using WebApplication1.Models.Issue;

namespace WebApplication1.Controllers
{
    public class IssueController : FailTrackerController
    {
        private readonly ApplicationDbContext _context;
        private readonly ICurrentUser _currentUser;

        // GET: Issue
        public IssueController(ApplicationDbContext context, ICurrentUser currentUser)
        {
            _context = context;
            _currentUser = currentUser;
        }
        //private SelectListItem[] GetAvailableUsers()
        //{
        //    return _context.Users.Select(u => new SelectListItem { Text = u.UserName, Value = u.Id }).ToArray();
        //}

        //private SelectListItem[] GetAvailableIssueTypes()
        //{
        //    return Enum.GetValues(typeof(IssueType))
        //        .Cast<IssueType>()
        //        .Select(t => new SelectListItem { Text = t.ToString(), Value = t.ToString() })
        //        .ToArray();
        //}
        [ChildActionOnly]
        public ActionResult YourIssuesWidget()
        {
            //var models = _context.Issues.Where(i => i.AssignedToUserName.Id == _currentUser.User.Id)
            //    .Select(i => new IssueSummaryViewModel
            //    {
            //        IssueId = i.IssueId,
            //        Subject = i.Subject,
            //        IssueType = i.IssueType,
            //        CreatedAt = i.CreatedAt,
            //        CreatorUserName = i.CreatorUserName.UserName
            //    });
            var models2 = _context.Issues.Where(i => i.AssignedTo.Id == _currentUser.User.Id).Project().To<IssueSummaryViewModel>().ToArray();
            return PartialView(models2);
        }
        [ChildActionOnly]
        public ActionResult CreatedByYouWidget()
        {
            //var models = _context.Issues.Where(i => i.CreatorUserName.Id == _currentUser.User.Id)
            //    .Select(i => new IssueSummaryViewModel
            //    {
            //        IssueId = i.IssueId,
            //        Subject = i.Subject,
            //        IssueType = i.IssueType,
            //        CreatedAt = i.CreatedAt,
            //        AssignedToUserName = i.AssignedToUserName.UserName
            //    });
            var models2 = _context.Issues.Where(i => i.Creator.Id == _currentUser.User.Id).Project().To<IssueSummaryViewModel>().ToArray();
            return PartialView(models2);
        }
        [ChildActionOnly]
        public ActionResult AssignmentStatsWidget()
        {
            var models2 = _context.Users.Project().To<AssignmentStatsViewModel>().ToArray();
            return PartialView(models2);
        }
        public ActionResult New()
        {
            var form = new NewIssueForm
            {
                //AvailableUsers = GetAvailableUsers(),
                //AvailableIssueTypes = GetAvailableIssueTypes()
            };
            return View(form);
        }
        [HttpPost, ValidateAntiForgeryToken,Log("Created Issue")]
        public ActionResult New(NewIssueForm form)
        {
            if (!ModelState.IsValid)
            {
                //form.AvailableUsers = GetAvailableUsers();
                //form.AvailableIssueTypes = GetAvailableIssueTypes();
                return View(form);
            }
            var assignedToUser = _context.Users.Single(u => u.Id == form.AssignedToUserId);
            var entity = form.MapTo<NewIssueForm, Issue>();
            entity.Creator = _currentUser.User;
            entity.AssignedTo = assignedToUser;
            _context.Issues.Add(entity);
            //_context.Issues.Add(new Issue(_currentUser.User, assignedToUser, form.IssueType, form.Subject, form.Body));
            _context.SaveChanges();
            //return RedirectToAction("Index", "Home");
            return RedirectToAction<HomeController>(c => c.Index()).WithSuccess("Issue created!!");
        }

        [Log("View Issue {id}")]
        public ActionResult View(int id)
        {
            //var models = _context.Issues
            //    .Include(i => i.AssignedToUserName)
            //    .Include(i => i.CreatorUserName).Select(x => new IssueDetailsViewModel
            //    {
            //        IssueId = x.IssueId,
            //        Subject = x.Subject,
            //        CreatedAt = x.CreatedAt,
            //        AssignedToUserName = x.AssignedToUserName.UserName,
            //        CreatorUserName = x.CreatorUserName.UserName,
            //        IssueType = x.IssueType,
            //        Body = x.Body
            //    }).SingleOrDefault(i => i.IssueId == id);
            var models = _context.Issues.Project().To< IssueDetailsViewModel >().SingleOrDefault(i => i.IssueId == id);

            if (models == null)
            {
                return RedirectToAction<HomeController>(c => c.Index()).WithError("Can not fin issue..");
            }

            return View(models);
        }
        [Log("Started to edit issue {id}")]
        public ActionResult Edit(int id)
        {
            //var issue = _context.Issues
            //    .Include(i => i.AssignedToUserName)
            //    .Include(i => i.CreatorUserName)
            //    .SingleOrDefault(i => i.IssueId == id);

            //if (issue == null)
            //{
            //    throw new ApplicationException("Issue not found!");
            //}

            //return View(new EditIssueForm
            //{
            //    IssueId = issue.IssueId,
            //    Subject = issue.Subject,
            //    AssignedToId = issue.AssignedToUserName.Id,
            //    AvailableUsers = GetAvailableUsers(),
            //    CreatorUserName = issue.CreatorUserName.UserName,
            //    IssueType = issue.IssueType,
            //    AvailableIssueTypes = GetAvailableIssueTypes(),
            //    Body = issue.Body
            //});

            var models = _context.Issues.Project().To<EditIssueForm>().SingleOrDefault(i => i.IssueId == id);
            if (models == null)
            {
                return RedirectToAction<HomeController>(c => c.Index()).WithError("Can not fin issue..");
            }

            //models.AvailableUsers = GetAvailableUsers();
            //models.AvailableIssueTypes = GetAvailableIssueTypes();
            return View(models);
        }
        [HttpPost, Log("Saving changes")]
        public ActionResult Edit(EditIssueForm form)
        {
            if (!ModelState.IsValid)
            {
                //form.AvailableUsers = GetAvailableUsers();
                //form.AvailableIssueTypes = GetAvailableIssueTypes();
                return View(form);
            }

            var issue = _context.Issues.SingleOrDefault(i => i.IssueId == form.IssueId);

            if (issue == null)
            {
                return RedirectToAction<HomeController>(c => c.Index()).WithError("Can not fin issue..");
            }

            var assignedToUser = _context.Users.Single(u => u.Id == form.AssignedToId);

            issue.Subject = form.Subject;
            issue.AssignedTo = assignedToUser;
            issue.Body = form.Body;
            issue.IssueType = form.IssueType;

            //return RedirectToAction("View", new { id = form.IssueId });
            return this.RedirectToAction(c => c.View(form.IssueId)).WithSuccess("update ok");
        }




        [HttpPost, ValidateAntiForgeryToken,Log("Delete Issue {id}")]
        public ActionResult Delete(int id)
        {
            var issue = _context.Issues.Find(id);
            if (issue==null)
            {
                return RedirectToAction<HomeController>(c => c.Index()).WithError("Can not fin issue..");
            }
            _context.Issues.Remove(issue);
            _context.SaveChanges();
            //return RedirectToAction("Index", "Home");
            return RedirectToAction<HomeController>(c => c.Index()).WithSuccess("Delete success");
        }
    }
}

WebApplication1/Views/Issue/AssignmentStatsWidget.cshtml
@model WebApplication1.Models.Issue.AssignmentStatsViewModel[]

<h3>All Issues</h3>
<table class="table table-hover">
    <thead>
    <tr>
        <th>User</th>
        <th>Enhancements</th>
        <th>Bugs</th>
        <th>Support</th>
        <th>Other</th>
    </tr>
    </thead>
    <tbody class="row-link" data-link="row">
    @foreach (var stat in Model)
    {
        <tr>
            <td>@stat.UserName</td>
            <td>@stat.Enhancements</td>
            <td>@stat.Bugs</td>
            <td>@stat.Support</td>
            <td>@stat.Other</td>
        </tr>
    }
    </tbody>
</table>

WebApplication1/Views/Issue/CreatedByYouWidget.cshtml
@model WebApplication1.Models.Issue.IssueSummaryViewModel[]

<h3>Created By You</h3>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Subject</th>
        <th>IssueIssueType</th>
        <th>Created At</th>
        <th>Assigned To</th>
    </tr>
    </thead>
    <tbody class="row-link" data-link="row">
    @foreach (var issue in Model)
    {
        <tr>
            <td>@Html.ActionLink(@issue.Subject, "View", "Issue", routeValues:new{id=@issue.IssueId}, htmlAttributes:null)</td>
            <td>@issue.IssueType</td>
            <td>@issue.CreatedAt.ToShortDateString()</td>
            <td>@issue.AssignedToUserName</td>
        </tr>   
    }
    </tbody>
</table>

WebApplication1/Views/Issue/Edit.cshtml
@using WebApplication1.Helpers
@model WebApplication1.Models.Issue.EditIssueForm
@{
    ViewBag.Title = "Edit" + Model.Subject;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Issue</h2>
@using (Html.BeginForm("Edit", "Issue", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.EditorForModel()

    @*@Html.HiddenFor(m => m.IssueId)
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.CreatorUserName)
        <div class="col-sm-10">
            @Html.EditorFor(m=>m.CreatorUserName)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.Subject)
        <div class="col-md-10">
            @Html.EditorFor(m => m.Subject)
            @Html.ValidationMessageFor(m => m.Subject)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.IssueType)
        <div class="col-md-10">
            @Html.EditorFor(m => m.IssueType)
            @Html.ValidationMessageFor(m => m.IssueType)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.AssignedToId)
        <div class="col-md-10">
            @Html.EditorFor(m => m.AssignedToId)
            @Html.ValidationMessageFor(m => m.AssignedToId)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.Body)
        <div class="col-md-10">
            @Html.EditorFor(m => m.Body)
            @Html.ValidationMessageFor(m => m.Body)
        </div>
    </div>*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save Changes" class="btn btn-default" />
        </div>
    </div>
}

WebApplication1/Views/Issue/IssueWidget.cshtml
@model WebApplication1.Models.Issue.IssueSummaryViewModel[]

<table class="table table-hover">
    <thead>
    <tr>
        <th>Subject</th>
        <th>Created At</th>
    </tr>
    </thead>
    <tbody class="row-link" data-link="row">
    @foreach (var issue in Model)
    {
        <tr>
            <td>@Html.ActionLink(@issue.Subject, "View", "Issue", routeValues:new{id=@issue.IssueId}, htmlAttributes:null)</td>
            <td>@issue.CreatedAt.ToShortDateString()</td>
        </tr>   
    }
    </tbody>
</table>

WebApplication1/Views/Issue/New.cshtml
@using WebApplication1.Helpers
@model WebApplication1.Models.Issue.NewIssueForm
@{
    ViewBag.Title = "New Issue";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Issue</h2>
@using (Html.BeginForm("New", "Issue", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.EditorForModel()
    @*<div class="form-group">
        @Html.BootstrapLabelFor(m => m.Subject)
        <div class="col-md-10">

            @Html.EditorFor(m => m.Subject)
            @Html.ValidationMessageFor(m => m.Subject)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.IssueType)
        <div class="col-md-10">
            @Html.EditorFor(m => m.IssueType)
            @Html.ValidationMessageFor(m => m.IssueType)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.AssignedToUserId)
        <div class="col-md-10">
            @Html.EditorFor(m => m.AssignedToUserId)
            @Html.ValidationMessageFor(m => m.AssignedToUserId)
        </div>
    </div>
    <div class="form-group">
        @Html.BootstrapLabelFor(m => m.Body)
        <div class="col-md-10">
            @Html.EditorFor(m => m.Body)
            @Html.ValidationMessageFor(m => m.Body)
        </div>
    </div>*@


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Issue" class="btn btn-default" />
        </div>
    </div>
}

WebApplication1/Views/Issue/View.cshtml
@model WebApplication1.Models.Issue.IssueDetailsViewModel
@{
    ViewBag.Title = Model.Subject;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    <img src="~/Content/IssueIssueIssueTypes/@(Model.IssueType).png" /> @Model.Subject
    <small class="pull-right">Received @Model.CreatedAt from @Model.CreatorUserName</small>
</h2>
<h4>Currently assigned to @Model.AssignedToUserName</h4>
<div class="well">
    <p class="lead">
        @Model.Body
    </p>
</div>
<div>
    @using (Html.BeginForm("Delete", "Issue", new { id = Model.IssueId }, FormMethod.Post, new { id = "delete-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ActionLink("Edit Issue", "Edit", "Issue", new { id = Model.IssueId }, new { @class = "btn btn-primary" })
        <button type="submit" class="btn btn-warning">Delete Issue</button>
    }
</div>
@section scripts
{
    <script>
        $(function () {
            $("#delete-form").on("submit", function () {
                return confirm("Are you sure you wish to delete this issue?  You cannot undo this action.");
            });
        });
    </script>
}

WebApplication1/Views/Issue/YourIssuesWidget.cshtml
@model WebApplication1.Models.Issue.IssueSummaryViewModel[]

<h3>Assigned To You</h3>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Subject</th>
        <th>IssueIssueType</th>
        <th>Created At</th>
        <th>Created By</th>
    </tr>
    </thead>
    <tbody class="row-link" data-link="row">
    @foreach (var issue in Model)
    {
        <tr>
            <td>@Html.ActionLink(@issue.Subject, "View", "Issue", routeValues:new{id=@issue.IssueId}, htmlAttributes:null)</td>
            <td>@issue.IssueType</td>
            <td>@issue.CreatedAt.ToShortDateString()</td>
            <td>@issue.CreatorUserName</td>
        </tr>   
    }
    </tbody>
</table>